apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: open-ocelot-python 
  janus-idp.io/tekton: open-ocelot-python
  backstage.io/kubernetes-id: open-ocelot-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: open-ocelot-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  